#!/usr/bin/expect -f
set timeout -1

spawn ssh -o StrictHostKeyChecking=no admin123@homeihc-ai-server "cd /opt/crm && echo P@ssw0rd | sudo -S rm -rf /opt/crm/property-dashboard/* && echo P@ssw0rd | sudo -S cp -r /tmp/property-dashboard/* /opt/crm/property-dashboard/ && echo P@ssw0rd | sudo -S chown -R admin123:admin123 /opt/crm/property-dashboard && echo P@ssw0rd | sudo -S docker compose up -d --build property-dashboard"
expect "*?assword:*"
send "P@ssw0rd\r"
expect eof
