#!/usr/bin/expect -f
set timeout -1
spawn scp -o StrictHostKeyChecking=no ./docker-compose.merged.yml admin123@homeihc-ai-server:/tmp/docker-compose.yml
expect "*?assword:*"
send "P@ssw0rd\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no admin123@homeihc-ai-server "echo P@ssw0rd | sudo -S cp /tmp/docker-compose.yml /opt/crm/docker-compose.yml && cd /opt/crm && sudo docker compose up -d"
expect "*?assword:*"
send "P@ssw0rd\r"
expect eof
