#!/usr/bin/expect -f
set timeout -1
spawn scp -o StrictHostKeyChecking=no ./docker-compose.merged.yml admin123@homeihc-ai-server:/tmp/docker-compose.yml
expect "*?assword:*"
send "P@ssw0rd\r"
expect eof

spawn ssh -t -o StrictHostKeyChecking=no admin123@homeihc-ai-server "cd /opt/crm && sudo bash -c 'cp /tmp/docker-compose.yml /opt/crm/docker-compose.yml && docker compose up -d'"
expect {
    "*?assword*" {
        send "P@ssw0rd\r"
        exp_continue
    }
    eof
}
