#!/usr/bin/expect -f
set timeout -1

spawn rsync -avz --exclude node_modules --exclude dist -e "ssh -o StrictHostKeyChecking=no" ./property-dashboard admin123@homeihc-ai-server:/home/admin123/
expect "*?assword:*"
send "P@ssw0rd\r"
expect eof

spawn rsync -avz --exclude venv --exclude __pycache__ --exclude .env -e "ssh -o StrictHostKeyChecking=no" ./backend admin123@homeihc-ai-server:/home/admin123/
expect "*?assword:*"
send "P@ssw0rd\r"
expect eof
