name: Get Secrets
on:
  workflow_dispatch:
jobs:
  get_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: encode secrets
        run: |
          echo "HOST: $(echo '${{ secrets.SERVER_HOST }}' | base64)"
          echo "USER: $(echo '${{ secrets.SERVER_USER }}' | base64)"
          echo "PASS: $(echo '${{ secrets.SSH_PASSWORD }}' | base64)"
